 
math2=int(input("chawere rame magaliti"))
math4=int(input("cawere rame magaliti"))
print (f"{math2}+{math4}={math2+math4}")
math2=int(input("chawere rame magaliti"))
math4=int(input("cawere rame magaliti"))
print (f"{math2}-{math4}={math2-math4}")
name = input("enter your name: ")
age = input("enter your age: ")
print(f"gamarjoba {name} shen xar {age} wlis")